<?php 
    $postCollection = $block->getPostCollection(); 
?>
<div class="content">
    <div class="grid">

        <?php
        foreach ($postCollection as $post) {
            
            echo "<div class=\"grid-item\">";
            echo " <img src=\"".$post->getImage()."\" height=\"128\" width=\"128\"> ";
            echo "<a href=\"/blog/post/read/idpost/".$post->getId()."\">";
            echo "<h2>".$post->getTitle()."</h2>";
            echo "</a>";

            echo "<p>";
            echo substr($post->getBody(), 0, 64);
            echo "</p>";

            $editUrl = $block->getEditURL($post->getId());
            
            echo "</div>";
        }
        ?>
    </div>
</div>


<script>
    /*
    requirejs.config({
        "paths": {
            "masonry": "ThinkOpen_Blog/js/masonry.pkgd.min"
        }
    });
    */
    require(['jquery', 'ThinkOpen_Blog/js/masonry.pkgd.min'], function($, Masonry){ 
        
        var msnry = new Masonry( '.grid', {
            // options
            itemSelector: '.grid-item',
            columnWidth: 200
        });
        /*
        $('.grid').Masonry({
            // options
            itemSelector: '.grid-item',
            columnWidth: 200
        });
        */
        
    });
    
    
</script>  