
<h1><?php echo $block->getBlogText(); ?></h1>





<div>

    <form method="post" action="/blog/create/save">
        
        <p>Titolo:<input name="title" type="text"></p>
        <p>Descrizione:<input name="description" type="text"></p>
        <p>Tags:<input name="tags" type="text"><small>(Inserisci i tag separati da virgole)</small></p>
        <p>Testo:<textarea name="body" rows="8"></textarea></p>

        <input type="submit">

    </form>

</div>