<?php 
    $postCollection = $block->getPostCollection(); 
?>

<div>
    
    <p>
        <a href="/admin/blog_admin/post/newpost"><button>Create new post</button></a>
    <p>

</div>

<br>

<div class="grid">

<?php
foreach ($postCollection as $post) {
    
    echo "<div class=\"grid-item\">";
    echo "<a href=\"/blog/post/read/idpost/".$post->getId()."\">";
    echo "<h2>".$post->getTitle()."</h2>";
    echo "</a>";

    echo "<p>";
    echo substr($post->getBody(), 0, 16);
    echo "</p>";

    $editUrl = $block->getEditURL($post->getId());
    
    //echo "<a href=\"/blog/post/edit/idpost/".$post->getId()."\">Edit</a>";
    echo "<a href=\"/admin/blog_admin/post/edit/idpost/".$post->getId()."\">Edit</a>";
    
    //echo "<a href=\"".$editUrl."\">Edit</a>";
    
    echo "</div>";
}
?>
</div>



<script>
    /*
    requirejs.config({
        "paths": {
            "masonry": "ThinkOpen_Blog/js/masonry.pkgd.min"
        }
    });
    */
    require(['jquery', 'ThinkOpen_Blog/js/masonry.pkgd.min'], function($, Masonry){ 
        
        var msnry = new Masonry( '.grid', {
            // options
            itemSelector: '.grid-item',
            columnWidth: 200
        });
        /*
        $('.grid').Masonry({
            // options
            itemSelector: '.grid-item',
            columnWidth: 200
        });
        */
        
    });
    
    
</script>  